Improved auto-install

diff --git a/install b/install
--- a/install
+++ b/install
@@ -4,15 +4,27 @@
 
 # Unless symlinks already exists, install wordstar keys into users local config
 # The symlink is left in case you have pointed it right here into a git working copy
+echo "Creating directory tree at ~/.xkb required by xkb to load files."
 mkdir -p ~/.xkb/symbols
 mkdir -p ~/.xkb/compat
 mkdir -p ~/.local/bin
 [[ ! -L ~/.xkb/symbols/wordstar ]] && cp wordstar ~/.xkb/symbols
-[[ ! -L ~/.xkb/symbols/wscompat ]] && cp wscompat ~/.xkb/compat
+[[ ! -L ~/.xkb/compat/wscompat ]] && cp wscompat ~/.xkb/compat
 [[ ! -L ~/.local/bin/wskeys ]] && cp wskeys ~/.local/bin
+echo "Done."
 
-# append wskeys to this user's .profile if it's not there, so that it gets automatically loaded at login
-grep -q "/wskeys$" ~/.profile || printf "\n# Load wordstar cursor control keys\n~/.local/bin/wskeys\n" >>~/.profile
+# Ask whether to append wskeys to this user's startup file if it's not there, so that it gets automatically loaded with the X session
+startup_file=~/.xinitrc
+if ! [[ -e "$startup_file" ]] || ! grep -q "/wskeys$" "$startup_file"; then
+  read -p "Shall I make wskeys load with the X Windows session by adding it to "$startup_file" (y/n)? " -n1 add_at_startup
+  echo
+  if [[ "$add_at_startup" == "y" ]]; then
+    [[ ! -e "$startup_file" ]] && touch "$startup_file"  # create it if necessary
+    printf "\n# Load wordstar cursor control keys when X session starts\n~/.local/bin/wskeys\n" >>"$startup_file"
+  fi
+fi
+
+# Tell the user if it needs to be added to the PATH
 if [[ "$PATH" != *"$HOME/.local/bin"* ]]; then
     echo "wskeys has been added to $HOME/.local/bin, so if you want to run 'wskeys' then"
     echo "you need to add ~/.local/bin to your PATH, or on some Linux distributions"
